# -*- coding: utf-8 -*-
"""1357 백준

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z_8VUpBt0YAb94ChddLjhfpwomq6u-JC
"""

def rev(s):
    if s:
        s=s[-1]+rev(s[:-1])
    return s


if __name__=="__main__":

  
    x,y= map(str,input().split())
    s1=int(rev(x))
    s2=int(rev(y))
    s3=rev(str(s1+s2))
    print(int(s3))