# -*- coding: utf-8 -*-
"""백준 2588

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HdHSJL1MXIxM6gXcHoHaj4TKtI2SUIXg
"""

#2588


n1=int(input())
n2=int(input())
a1=n1*(n2%10)
a2=n1*((n2//10)%10)
a3=n1*(n2//100)

print(a1)
print(a2)
print(a3)
print(n1*n2)