# -*- coding: utf-8 -*-
"""백준 10699

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IxDYTDGvkR7lwEiMdWxoqKOqxQerEsKe
"""

#10699

import datetime

now=datetime.datetime.now()

a=now.strftime("%Y-%m-%d")
print(a)