# -*- coding: utf-8 -*-
"""백준5543

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17TjbLn6zR36c0SX_EiCLuz8QHEdlc1lS
"""

#5543

h=int(input())      #상덕버거
m=int(input())      #중덕버거
l=int(input())      #하덕버거
c=int(input())      #콜라
d=int(input())      #사이다

set1=h+c-50
set2=h+d-50
set3=m+l-50
set4=m+c-50
set5=l+c-50
set6=l+d-50

array=([set1,set2,set3,set4,set5,set6])

print(min(array))