# -*- coding: utf-8 -*-
"""백준 2163

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XJaUMIOaOmj8XqoEJPFQ81wDvkHqM_pN
"""

#2163

n,m=map(int,input().split())

choco=n*m-1

print(choco)