# -*- coding: utf-8 -*-
"""백준 1000

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15bM33YNmSxtwr7ZkjUdEcvdXCN_pwRQB
"""

#1000

a,b=map(int,input().split())
print(a+b)