# -*- coding: utf-8 -*-
"""백준1004

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K1j2HgFErPZUSquxRFceGr4sWFCwB-WF
"""

T=int(input()) #테스트케이스 개수

for i in range(T):
    x1,y1,x2,y2=map(int,input().split())
    n=int(input())
    count=0

    for j in range(n):
        cx,cy,r=map(int,input().split())
        d1=((cx-x1)**2+(cy-y1)**2)**0.5  #출발점과 행성계의 거리 **0.5는 제곱근 **2는 제곱
        d2=((cx-x2)**2+(cy-y2)**2)**0.5   #도착점과 행성계의 거리
        
        if (d1>r and d2<r) or (d1<r and d2>r):
            count=count+1
        
    print(count)