# -*- coding: utf-8 -*-
"""기초100제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14AfWxi976MlUZdkygiOTtg6lVSLIYynV
"""

print("Hello") #1번

print("Hello World") #2

print("Hello")
print("World") #3

print("'Hello'") #4

print('"Hello World"') #5

print("\"!@#$%^&*()\'") #6

print("\"C:\Download\\'hello'.py\"") #7

print('print("Hello\\nWorld")') #8

a=str(input())
print(a) #9

a=int(input())
print(a) #10

a=float(input())
print(a) #11

a=input()
b=input()
print(a)
print(b) #12

a=str(input())
b=str(input())
print(b)
print(a) #13

a=float(input())
print(a)
print(a)
print(a) #14

a,b=map(int,input().split())
print(a)
print(b) #15

a,b=map(str,input().split())
print("%s %s" %(b,a)) #16

a=str(input())
print("%s %s %s" %(a,a,a)) #17

a,b=map(int,input().split(":"))
print("%d:%d" %(a,b)) #18

y,m,d=map(int,input().split("."))
print("%d-%d-%d" %(d,m,y)) #19

a=input()
a=a.replace("-","")
print(a) #20

a=input()
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4]) #21

a=str(input())
print("%s %s %s" %(a[0:2],a[2:4],a[4:6])) #22

a,b,c=map(str,input().split(":",2))
print("{}" .format(b)) #23 Q.왜 str일까?

w1,w2=input().split()
a=w1+w2
print(a) #24

a,b=map(int,input().split())
c=a+b
print(c) #25

a=float(input())
b=float(input())
print(a+b) #26

a=int(input())
print("%x" %a) #27 16진수

a=int(input())
print("%X" %a) #28 16진수

a=input()
b=int(a,16)
print("%o" %b) #29 16->8

a=input()
print(ord(a)) #아스키코드 문자열->숫자 #30

a=int(input())
print(chr(a)) #숫자->문자열 (아스키코드) #31

a=int(input())
print(-a) #32

a=input()
n=ord(a)
print(chr(n+1)) #33

a,b=map(int,input().split())
print(a-b) #34

a,b=map(float,input().split())
print(a*b) #35

w,n=input().split()
print(w*int(n)) #36

n=int(input())
s=input()
print(s*n) #37

a,b=map(int,input().split())
print(a**b) #38

a,b=map(float,input().split())
print(a**b)  #39

a,b=map(int,input().split())
print(a//b) #40

a,b=map(int,input().split())
print(a%b) #41

f=float(input())
print(round(f,2)) #42

a,b=map(float,input().split())
print(round(a/b,3)) #43

a,b=map(int,input().split())
print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a%b)
print(round(a/b,2)) #44

a,b,c=map(int,input().split())
s=a+b+c
m=round(s/3,2)
print(s,m) #45

a=int(input())
print(a<<1) #46

a,b=map(int,input().split())
print(a<<b) #47

a,b=map(int,input().split())
if a <b :
    print("True")
else:
    print("False") #48

a,b=map(int,input().split())
if a==b :
    print("True")
else :
    print("False") #49 같다라는 표시는 ==이다. 혼돈금지

a,b=map(int,input().split())
if b>=a : 
    print("True")
else:
    print("False") #50

a,b=map(int,input().split())
if a!=b:
    print("True")
else:
    print("False") #51

a=int(input())
print(bool(a)) #52 bool함수 true,false 출력

a=int(input())
print(not(bool(a))) #53 bool반대값 출력 위해서 not 이용

a,b=map(int,input().split())
print(bool(a)and bool(b)) #54 논리연산자 and 이용

a,b=map(int,input().split())
print(bool(a) or bool(b)) #55

a,b=map(int,input().split())
c=bool(a)
d=bool(b)
print((not(c)and d )or(not(d)and c)) #56 이거 헷갈리넹

a,b=map(int,input().split())
c=bool(a)
d=bool(b)
if c==b:
    print("True")
else:
    print("False") #57

a,b=map(int,input().split())
c=bool(a)
d=bool(b)
if not(c or b):
    print("True")
else:
    print("False") #58

a=int(input())
print(~a) #59

a,b=map(int,input().split())
print(a&b) #60

a,b=map(int,input().split())
print(a|b) #61 파이프연산자 어떻게 치지..?

a,b=map(int,input().split())
print(a^b) #62

a,b=map(int,input().split())
if a>b :
    print(a)
else:
    print(b) #63

a,b,c=map(int,input().split())
array=([a,b,c])
print(min(array)) #64

a,b,c=map(int,input().split())
if a%2==0:
    print(a)
if b%2==0:
    print(b)
if c%2==0:
    print(c) #65

a,b,c=map(int,input().split())
if a%2==0:
    print("even")
else:
    print("odd")
if b%2==0:
    print("even")
else:
    print("odd")
if c%2==0:
    print("even")
else:
    print("odd") #66

n=int(input())
if n>0:
    if n%2==0:
        print("C")
    else:
        print("D")
if n<0:
    if n%2==0:
        print("A")
    else:
        print("B") #67

s=int(input())
if s>=90:
    print("A")
elif s>=70:
    print("B")
elif s>=40:
    print("C")
else: 
    print("D") #68

s=str(input())
if s=="A":
    print("best!!!")
elif s=="B":
    print("good!!")
elif s=="C":
    print("run!")
elif s=="D":
    print("slowly~")
else:
    print("what?") #69

a=int(input())
if a//3==1:
    print("spring")
elif a//3==2:
    print("summer")
elif a//3==3:
    print("fall")
else:
    print("winter") #70

n=1
while n!=0:
    n=int(input())
    if n!=0:
        print(n) #71

n=int(input())
while n!=0:
    print(n)
    n=n-1 #72

n=int(input())
while n!=0:
    n=n-1
    print(n) #73

n=ord(input())
z=ord("a")

while z<=n:
    print(chr(z), end=" ")
    z=z+1 #74

n=int(input())
a=-1

while n!=0:
    a=a+1
    if a<=n:
        print(a) #75 -> 시간초과,,,

n=int(input())
a=-1

while a<n:
    a=a+1
    print(a) #75 성공!

n=int(input())
a=-1

while a<n:
    a=a+1
    print(a) #76

n=int(input())

for i in range(n+1):
    print(i) #76(2)

n=int(input())
sum=0

for i in range(n+1):
    if i%2==0:
        sum=sum+i
print(sum) #77  왜 while은 안될까?

a=ord("q")
n=1

while n!=a:
    n=ord(input())
    if n!=a:
        print(chr(n))
print(chr(a))   #78

a=0
sum=0
b=int(input())
i=1

while True:
    a=a+1
    while i<=a:
        sum=sum+i
        if sum==b:
            print(a)
        i=i+1  #79 -> 시간 초과

a=0
sum=0
b=int(input())
i=1

while True:
    a=a+1
    for i in range(a):
        sum=sum+i
        if sum==b:
            print(a)
        i=i+1  #79 -> 시간초과

sum=0
b=int(input())
i=1


while i<=i+1:
    sum=sum+i
    if sum==b:
        print(i)
    i=i+1  #79 -> 시간초과

sum=0

for i in range(11):
    sum=sum+i
print(sum)

sum=0
b=int(input())
n=1

while sum<b:
    sum=sum+n
    n=n+1

print(n-1)      #79번 잘 모르겠음 ㅜㅜ

n,m=map(int,input().split())

for i in range(1,n+1):
    for j in range(1,m+1):
        print(i,j)  #80

n=int(input(),16)
for i in range(1,16):
    print('%X'%n,'*%X'%i,'=%X'%(n*i),sep='')
#81

n=int(input())

for i in range(1,n+1):
    if (i%10==3) or (i%10==6) or (i%10==9):         #변수%10==어떤수 -> 어떤수가 포함된거 구하기
        print("X", end=' ')
    else:
        print(i,end=' ')    #82

r,g,b=map(int,input().split())
count=0

for i in range(0,r):
    for j in range(0,g):
        for p in range(0,b):
            print(i,j,p)
            count=count+1
print(count)            #83

h,b,c,s=map(int,input().split())

a=(h*b*c*s)/8/1024/1024

print("%.1f MB" %a)     #84

w,h,b=map(int,input().split())

a=round(((w*h*b)/8/1024/1024),2)

print("%.2f MB" %a)       #85

n=int(input())
sum=0

for i in range(1,n+1):
        sum=sum+i
        i=i+1
        if sum>=n:
            break
print(sum)            #86

n=int(input())

for i in range(1,n+1):
    if i%3==0:
        continue
    else: 
        print(i,end=' ')        #87

a,d,n=map(int,input().split())

value=a+(n-1)*d
print("%d" %value)      #88

a,r,n=map(int,input().split())

v=a*r**(n-1)
print("%d" %v)      #89

a,m,d,n=map(int,input().split())

for i in range(n-1):
    a=a*m+d
print("%d" %a)      #90

a,b,c=map(int,input().split())

d=1
while d%a!=0 or d%b!=0 or d%c!=0 :
    d=d+1
print(d)        #91

n = int(input())
random = list(map(int, input().split()))
check_list = [0] * 23

for i in range(n):
    check_list[random[i]-1] += 1

for j in check_list:
    print(j, end=' ')     #92

n=int(input())
random=list(map(int,input().split()))

for i in range(n-1,-1,-1):
    print(random[i], end=' ')           #93

n=int(input())
random=list(map(int,input().split()))

print(min(random))              #94

# 95 ->다시풀기
n = int(input())
white = []

for i in range(n):
    x, y = map(int, input().split())
    white.append((x,y))

for j in range(19):
    for k in range(19):
        temp = 0
        if (j+1, k+1) in white:
            temp = 1
        print(temp, end = ' ')
    print()

# 96 --> 다시 풀기
a = [[0]*19]*19

for i in range(19):
    a[i] = list(map(int, input().split()))

n = int(input())

for k in range(n):
    x, y = map(int, input().split())

    for l in range(19):
        if a[x-1][l] == 0: # x 축 뒤집기
            a[x-1][l] = 1
        else :
            a[x-1][l] = 0
        if a[l][y-1] == 0: # y 축 뒤집기
            a[l][y-1] = 1
        else:
            a[l][y-1] = 0

for o in range(19):
    for p in range(19):
        print(a[o][p], end = ' ')
    print()

# 97 -> 다시풀기
h, w = map(int ,input().split())
n = int(input())
a = [[0] * w for _ in range(h)]

for i in range(n):
    l, d, x, y = map(int,input().split())
    for j in range(l):
        if d == 0:
            a[x-1][y-1+j] = 1
        else:
            a[x-1+j][y-1] = 1

for k in range(h):
    for l in range(w):
        print(a[k][l], end = ' ')
    print()

# 98 -> 다시풀기
a = []

for i in range(10):
    a.append(list(map(int, input().split())))

x = 1
y = 1

while True:
    if a[x][y] == 0:
        a[x][y] = 9
    elif a[x][y] == 2:
        a[x][y] = 9
        break;
    
    if a[x][y+1] == 1 and a[x+1][y] == 1:
        break
    
    if a[x][y+1] != 1:
        y = y + 1
    elif a[x+1][y] != 1:
        x = x + 1
    
for i in range(10):
    for j in range(10):
        print(a[i][j], end = ' ')
    print()